"""refactor workflow_nodes add version system

Revision ID: 457c2176c7ac
Revises: f000991a1dff
Create Date: 2025-12-24 22:42:10.760724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '457c2176c7ac'
down_revision: Union[str, Sequence[str], None] = 'f000991a1dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. 创建版本表
    op.create_table('workflow_node_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False, comment="版本号 (e.g. '1.0.0' or '1.0.0-SNAPSHOT')"),
    sa.Column('version_type', sa.String(), nullable=False, comment='版本类型: SNAPSHOT 或 RELEASE'),
    sa.Column('parameters_schema', sa.JSON(), nullable=False, comment='输入参数 Schema'),
    sa.Column('outputs_schema', sa.JSON(), nullable=False, comment='输出参数 Schema'),
    sa.Column('ui_config', sa.JSON(), nullable=False, comment='UI 配置'),
    sa.Column('handler_path', sa.String(), nullable=False, comment='后端执行器路径'),
    sa.Column('changelog', sa.Text(), nullable=True, comment='版本变更说明'),
    sa.Column('published_at', sa.DateTime(), nullable=False, comment='发布时间'),
    sa.ForeignKeyConstraint(['node_id'], ['workflow_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_node_versions_id'), 'workflow_node_versions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_node_versions_node_id'), 'workflow_node_versions', ['node_id'], unique=False)

    # 2. 添加新的草稿字段 (先允许 NULL)
    op.add_column('workflow_nodes', sa.Column('draft_parameters_schema', sa.JSON(), nullable=True, comment='草稿 - 输入参数 Schema'))
    op.add_column('workflow_nodes', sa.Column('draft_outputs_schema', sa.JSON(), nullable=True, comment='草稿 - 输出参数 Schema'))
    op.add_column('workflow_nodes', sa.Column('draft_ui_config', sa.JSON(), nullable=True, comment='草稿 - UI 配置'))
    op.add_column('workflow_nodes', sa.Column('draft_handler_path', sa.String(), nullable=True, comment='草稿 - 后端执行器路径'))
    op.add_column('workflow_nodes', sa.Column('latest_snapshot', sa.String(), nullable=True, comment="最新快照版本号 (e.g. '1.2.0-SNAPSHOT')"))
    op.add_column('workflow_nodes', sa.Column('latest_release', sa.String(), nullable=True, comment="最新发行版本号 (e.g. '1.1.0')"))

    # 3. 迁移现有数据: 复制旧字段到新的 draft_ 字段
    op.execute("""
        UPDATE workflow_nodes SET
            draft_parameters_schema = COALESCE(parameters_schema, '{}'),
            draft_outputs_schema = COALESCE(outputs_schema, '{}'),
            draft_ui_config = COALESCE(ui_config, '{}'),
            draft_handler_path = handler_path
    """)

    # 4. 设置 NOT NULL 约束
    op.alter_column('workflow_nodes', 'draft_parameters_schema', nullable=False)
    op.alter_column('workflow_nodes', 'draft_outputs_schema', nullable=False)
    op.alter_column('workflow_nodes', 'draft_ui_config', nullable=False)

    # 5. 删除旧字段
    op.drop_column('workflow_nodes', 'parameters_schema')
    op.drop_column('workflow_nodes', 'type')
    op.drop_column('workflow_nodes', 'outputs_schema')
    op.drop_column('workflow_nodes', 'handler_path')
    op.drop_column('workflow_nodes', 'is_active')
    op.drop_column('workflow_nodes', 'ui_config')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_nodes', sa.Column('ui_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='前端 UI 配置 (宽高, Handles, Defaults)'))
    op.add_column('workflow_nodes', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否启用'))
    op.add_column('workflow_nodes', sa.Column('handler_path', sa.VARCHAR(), autoincrement=False, nullable=False, comment="后端执行器路径 (e.g. 'server.etl.process.handlers.CSVLoader')"))
    op.add_column('workflow_nodes', sa.Column('outputs_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='输出参数 Schema'))
    op.add_column('workflow_nodes', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False, comment='节点类型 (generic: 通用表单, custom: 定制UI)'))
    op.add_column('workflow_nodes', sa.Column('parameters_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='输入参数 JSON Schema'))
    op.alter_column('workflow_nodes', 'icon',
               existing_type=sa.VARCHAR(),
               comment='图标名称或路径',
               existing_comment='图标名称',
               existing_nullable=True)
    op.alter_column('workflow_nodes', 'name',
               existing_type=sa.VARCHAR(),
               comment="唯一标识符 (Internal ID, e.g. 'csv_loader')",
               existing_comment="唯一标识符 (e.g. 'csv_loader')",
               existing_nullable=False)
    op.drop_column('workflow_nodes', 'latest_release')
    op.drop_column('workflow_nodes', 'latest_snapshot')
    op.drop_column('workflow_nodes', 'draft_handler_path')
    op.drop_column('workflow_nodes', 'draft_ui_config')
    op.drop_column('workflow_nodes', 'draft_outputs_schema')
    op.drop_column('workflow_nodes', 'draft_parameters_schema')
    op.drop_index(op.f('ix_workflow_node_versions_node_id'), table_name='workflow_node_versions')
    op.drop_index(op.f('ix_workflow_node_versions_id'), table_name='workflow_node_versions')
    op.drop_table('workflow_node_versions')
    # ### end Alembic commands ###
