"""create_workflow_nodes_table

Revision ID: 46b5cc096aa5
Revises: a67e1f9dc5c5
Create Date: 2025-12-21 23:14:48.565610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46b5cc096aa5'
down_revision: Union[str, Sequence[str], None] = 'a67e1f9dc5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="唯一标识符 (Internal ID, e.g. 'csv_loader')"),
    sa.Column('title', sa.String(), nullable=False, comment="显示名称 (e.g. 'CSV 加载器')"),
    sa.Column('category', sa.String(), nullable=False, comment="核心分类 (e.g. 'input', 'transform')"),
    sa.Column('type', sa.String(), nullable=False, comment='节点类型 (generic: 通用表单, custom: 定制UI)'),
    sa.Column('icon', sa.String(), nullable=True, comment='图标名称或路径'),
    sa.Column('description', sa.Text(), nullable=True, comment='节点功能描述'),
    sa.Column('parameters_schema', sa.JSON(), nullable=False, comment='输入参数 JSON Schema'),
    sa.Column('ui_config', sa.JSON(), nullable=False, comment='前端 UI 配置 (宽高, Handles, Defaults)'),
    sa.Column('handler_path', sa.String(), nullable=False, comment="后端执行器路径 (e.g. 'server.etl.process.handlers.CSVLoader')"),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_nodes_category'), 'workflow_nodes', ['category'], unique=False)
    op.create_index(op.f('ix_workflow_nodes_id'), 'workflow_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_nodes_name'), 'workflow_nodes', ['name'], unique=True)
    
    op.alter_column('data_table_configs', 'last_published_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='上次成功发布(物理建表)的时间',
               existing_nullable=True)
    op.alter_column('etl_task_configs', 'graph_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='前端图编辑器数据',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('etl_task_configs', 'graph_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='前端图编辑器数据',
               existing_nullable=True)
    op.alter_column('data_table_configs', 'last_published_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='上次成功发布(物理建表)的时间',
               existing_nullable=True)
    
    op.drop_index(op.f('ix_workflow_nodes_name'), table_name='workflow_nodes')
    op.drop_index(op.f('ix_workflow_nodes_id'), table_name='workflow_nodes')
    op.drop_index(op.f('ix_workflow_nodes_category'), table_name='workflow_nodes')
    op.drop_table('workflow_nodes')
    # ### end Alembic commands ###