"""add_etl_task_config

Revision ID: 4c137122a529
Revises: bae792799715
Create Date: 2025-12-07 18:56:47.897809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c137122a529'
down_revision: Union[str, Sequence[str], None] = 'bae792799715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_task_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='任务名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='任务描述'),
    sa.Column('source_type', sa.String(), nullable=False, comment='数据源类型'),
    sa.Column('source_config', sa.JSON(), nullable=False, comment='数据源详细配置参数'),
    sa.Column('pipeline_config', sa.JSON(), nullable=False, comment='处理链路配置'),
    sa.Column('batch_size', sa.Integer(), nullable=True, comment='批次处理大小'),
    sa.Column('schedule', sa.String(), nullable=True, comment='Crontab 定时表达式'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etl_task_configs_id'), 'etl_task_configs', ['id'], unique=False)
    op.create_index(op.f('ix_etl_task_configs_name'), 'etl_task_configs', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etl_task_configs_name'), table_name='etl_task_configs')
    op.drop_index(op.f('ix_etl_task_configs_id'), table_name='etl_task_configs')
    op.drop_table('etl_task_configs')
    # ### end Alembic commands ###
