"""init_correct_schema

Revision ID: 60d403367b7a
Revises: 
Create Date: 2025-12-13 18:18:12.991051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60d403367b7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Handle existing Enum type to preventing collision
    op.execute("DROP TYPE IF EXISTS tablestatus CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_task_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='任务名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='任务描述'),
    sa.Column('source_type', sa.String(), nullable=False, comment='数据源类型'),
    sa.Column('source_config', sa.JSON(), nullable=False, comment='数据源详细配置参数'),
    sa.Column('pipeline_config', sa.JSON(), nullable=False, comment='处理链路配置'),
    sa.Column('batch_size', sa.Integer(), nullable=True, comment='批次处理大小'),
    sa.Column('schedule', sa.String(), nullable=True, comment='Crontab 定时表达式'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etl_task_configs_id'), 'etl_task_configs', ['id'], unique=False)
    op.create_index(op.f('ix_etl_task_configs_name'), 'etl_task_configs', ['name'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_name', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_name'), 'events', ['event_name'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_process_name'), 'events', ['process_name'], unique=False)
    op.create_table('table_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False, comment='分类编码 (e.g., market_data)'),
    sa.Column('name', sa.String(), nullable=False, comment='显示名称'),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_table_categories_id'), 'table_categories', ['id'], unique=False)
    op.create_table('data_table_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='显示名称'),
    sa.Column('table_name', sa.String(), nullable=False, comment='物理表名'),
    sa.Column('description', sa.Text(), nullable=False, comment='详细描述'),
    sa.Column('status', sa.Enum('DRAFT', 'CREATED', 'ARCHIVED', name='tablestatus'), nullable=False),
    sa.Column('last_published_at', sa.DateTime(), nullable=True, comment='上次成功发布(物理建表)的时间'),
    sa.Column('columns_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='列定义元数据'),
    sa.Column('indexes_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='索引定义元数据'),
    sa.Column('partition_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='分区策略配置'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['table_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name')
    )
    op.create_index(op.f('ix_data_table_configs_id'), 'data_table_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_table_configs_id'), table_name='data_table_configs')
    op.drop_table('data_table_configs')
    op.drop_index(op.f('ix_table_categories_id'), table_name='table_categories')
    op.drop_table('table_categories')
    op.drop_index(op.f('ix_events_process_name'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_name'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_etl_task_configs_name'), table_name='etl_task_configs')
    op.drop_index(op.f('ix_etl_task_configs_id'), table_name='etl_task_configs')
    op.drop_table('etl_task_configs')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS tablestatus CASCADE")
