"""remove_workflow_nodes_tables

Revision ID: 67cab60bda74
Revises: 457c2176c7ac
Create Date: 2025-12-27 22:54:57.288719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67cab60bda74'
down_revision: Union[str, Sequence[str], None] = '457c2176c7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_node_versions_id'), table_name='workflow_node_versions')
    op.drop_index(op.f('ix_workflow_node_versions_node_id'), table_name='workflow_node_versions')
    op.drop_table('workflow_node_versions')
    op.drop_index(op.f('ix_workflow_nodes_category'), table_name='workflow_nodes')
    op.drop_index(op.f('ix_workflow_nodes_id'), table_name='workflow_nodes')
    op.drop_index(op.f('ix_workflow_nodes_name'), table_name='workflow_nodes')
    op.drop_table('workflow_nodes')
    op.drop_index(op.f('idx_daily_bars_copy_copy_trade_date'), table_name='daily_bars_copy_copy')
    op.drop_table('daily_bars_copy_copy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_bars_copy_copy',
    sa.Column('trade_date', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='交易日期'),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='开盘价'),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='最高价'),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='最低价'),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='收盘价'),
    sa.Column('vol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='成交量'),
    sa.Column('ts_code1', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='股票代码'),
    comment='存储股票日线级别OHLCV数据'
    )
    op.create_index(op.f('idx_daily_bars_copy_copy_trade_date'), 'daily_bars_copy_copy', ['trade_date'], unique=True)
    op.create_table('workflow_nodes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('workflow_nodes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False, comment="唯一标识符 (Internal ID, e.g. 'csv_loader')"),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False, comment="显示名称 (e.g. 'CSV 加载器')"),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False, comment="核心分类 (e.g. 'input', 'transform')"),
    sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True, comment='图标名称或路径'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='节点功能描述'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('draft_parameters_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='草稿 - 输入参数 Schema'),
    sa.Column('draft_outputs_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='草稿 - 输出参数 Schema'),
    sa.Column('draft_ui_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='草稿 - UI 配置'),
    sa.Column('draft_handler_path', sa.VARCHAR(), autoincrement=False, nullable=True, comment='草稿 - 后端执行器路径'),
    sa.Column('latest_snapshot', sa.VARCHAR(), autoincrement=False, nullable=True, comment="最新快照版本号 (e.g. '1.2.0-SNAPSHOT')"),
    sa.Column('latest_release', sa.VARCHAR(), autoincrement=False, nullable=True, comment="最新发行版本号 (e.g. '1.1.0')"),
    sa.Column('is_deprecated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='workflow_nodes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_workflow_nodes_name'), 'workflow_nodes', ['name'], unique=True)
    op.create_index(op.f('ix_workflow_nodes_id'), 'workflow_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_nodes_category'), 'workflow_nodes', ['category'], unique=False)
    op.create_table('workflow_node_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False, comment="版本号 (e.g. '1.0.0' or '1.0.0-SNAPSHOT')"),
    sa.Column('version_type', sa.VARCHAR(), autoincrement=False, nullable=False, comment='版本类型: SNAPSHOT 或 RELEASE'),
    sa.Column('parameters_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='输入参数 Schema'),
    sa.Column('outputs_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='输出参数 Schema'),
    sa.Column('ui_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='UI 配置'),
    sa.Column('handler_path', sa.VARCHAR(), autoincrement=False, nullable=False, comment='后端执行器路径'),
    sa.Column('changelog', sa.TEXT(), autoincrement=False, nullable=True, comment='版本变更说明'),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='发布时间'),
    sa.ForeignKeyConstraint(['node_id'], ['workflow_nodes.id'], name=op.f('workflow_node_versions_node_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_node_versions_pkey'))
    )
    op.create_index(op.f('ix_workflow_node_versions_node_id'), 'workflow_node_versions', ['node_id'], unique=False)
    op.create_index(op.f('ix_workflow_node_versions_id'), 'workflow_node_versions', ['id'], unique=False)
    # ### end Alembic commands ###
