"""rebuild_data_table_schema_v2

Revision ID: 911330050425
Revises: 4c137122a529
Create Date: 2025-12-07 20:34:13.302740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '911330050425'
down_revision: Union[str, Sequence[str], None] = '4c137122a529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False, comment='分类编码 (e.g., market_data)'),
    sa.Column('name', sa.String(), nullable=False, comment='显示名称'),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_table_categories_id'), 'table_categories', ['id'], unique=False)
    op.create_table('data_table_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='显示名称'),
    sa.Column('table_name', sa.String(), nullable=False, comment='物理表名'),
    sa.Column('description', sa.Text(), nullable=False, comment='详细描述'),
    sa.Column('status', sa.Enum('DRAFT', 'CREATED', 'ARCHIVED', name='tablestatus'), nullable=False),
    sa.Column('columns_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='列定义元数据'),
    sa.Column('indexes_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='索引定义元数据'),
    sa.Column('partition_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='分区策略配置'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['table_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name')
    )
    op.create_index(op.f('ix_data_table_configs_id'), 'data_table_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_table_configs_id'), table_name='data_table_configs')
    op.drop_table('data_table_configs')
    op.drop_index(op.f('ix_table_categories_id'), table_name='table_categories')
    op.drop_table('table_categories')
    # ### end Alembic commands ###
