"""initial_full_schema

Revision ID: 9a53d9effce3
Revises: 
Create Date: 2025-12-07 23:17:23.126082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a53d9effce3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_bars')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_bars',
    sa.Column('ts_code', sa.VARCHAR(), autoincrement=False, nullable=False, comment='股票代码'),
    sa.Column('trade_date', sa.VARCHAR(), autoincrement=False, nullable=False, comment='交易日期'),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='开盘价'),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='最高价'),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='最低价'),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='收盘价'),
    sa.Column('vol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='成交量'),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date', name=op.f('daily_bars_pkey')),
    comment='存储股票日线级别OHLCV数据'
    )
    # ### end Alembic commands ###
