"""add_graph_config_to_etltaskconfig

Revision ID: a67e1f9dc5c5
Revises: 60d403367b7a
Create Date: 2025-12-14 22:41:16.804837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67e1f9dc5c5'
down_revision: Union[str, Sequence[str], None] = '60d403367b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_task_configs', sa.Column('graph_config', sa.JSON(), nullable=True, comment='前端图编辑器数据'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etl_task_configs', 'graph_config')
    # ### end Alembic commands ###
