"""add_type_to_etl_task_config

Revision ID: e545317e5ba8
Revises: 46b5cc096aa5
Create Date: 2025-12-24 22:09:19.518543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e545317e5ba8'
down_revision: Union[str, Sequence[str], None] = '46b5cc096aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_bars')
    op.drop_index(op.f('idx_daily_bars_copy1_trade_date'), table_name='daily_bars_copy1')
    op.drop_table('daily_bars_copy1')
    op.add_column('etl_task_configs', sa.Column('type', sa.String(), server_default='etl', nullable=False, comment='任务类型'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etl_task_configs', 'type')
    op.create_table('daily_bars_copy1',
    sa.Column('ts_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='股票代码'),
    sa.Column('trade_date', sa.VARCHAR(length=8), autoincrement=False, nullable=False, comment='交易日期'),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='开盘价'),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='最高价'),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='最低价'),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='收盘价'),
    sa.Column('vol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='成交量'),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date', 'open', 'close', name=op.f('daily_bars_copy_pkey')),
    comment='存储股票日线级别OHLCV数据'
    )
    op.create_index(op.f('idx_daily_bars_copy1_trade_date'), 'daily_bars_copy1', ['trade_date'], unique=True)
    op.create_table('daily_bars',
    sa.Column('ts_code', sa.VARCHAR(), autoincrement=False, nullable=False, comment='股票代码'),
    sa.Column('trade_date', sa.VARCHAR(), autoincrement=False, nullable=False, comment='交易日期'),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='开盘价'),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='最高价'),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='最低价'),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='收盘价'),
    sa.Column('vol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='成交量'),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date', name=op.f('daily_bars_pkey')),
    comment='存储股票日线级别OHLCV数据1111'
    )
    # ### end Alembic commands ###
