"""add outputs_schema to workflow_nodes

Revision ID: f000991a1dff
Revises: e545317e5ba8
Create Date: 2025-12-24 22:14:25.717151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f000991a1dff'
down_revision: Union[str, Sequence[str], None] = 'e545317e5ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First add column as nullable
    op.add_column('workflow_nodes', sa.Column('outputs_schema', sa.JSON(), nullable=True, comment='输出参数 Schema'))
    # Set default value for existing rows
    op.execute("UPDATE workflow_nodes SET outputs_schema = '{}' WHERE outputs_schema IS NULL")
    # Then make it non-nullable
    op.alter_column('workflow_nodes', 'outputs_schema', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_nodes', 'outputs_schema')
    # ### end Alembic commands ###
